# Form implementation generated from reading ui file './res/ui/editlinkwindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditLinkWindow(object):
    def setupUi(self, EditLinkWindow):
        EditLinkWindow.setObjectName("EditLinkWindow")
        EditLinkWindow.resize(600, 92)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditLinkWindow.sizePolicy().hasHeightForWidth())
        EditLinkWindow.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditLinkWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.link = QtWidgets.QLineEdit(parent=EditLinkWindow)
        self.link.setObjectName("link")
        self.verticalLayout.addWidget(self.link)
        self.buttons = QtWidgets.QDialogButtonBox(parent=EditLinkWindow)
        self.buttons.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttons.setObjectName("buttons")
        self.verticalLayout.addWidget(self.buttons)

        self.retranslateUi(EditLinkWindow)
        self.buttons.accepted.connect(EditLinkWindow.accept) # type: ignore
        self.buttons.rejected.connect(EditLinkWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditLinkWindow)

    def retranslateUi(self, EditLinkWindow):
        _translate = QtCore.QCoreApplication.translate
        EditLinkWindow.setWindowTitle(_translate("EditLinkWindow", "Set URL"))
        self.link.setPlaceholderText(_translate("EditLinkWindow", "https://www.youtube.com/watch?v=iBeoFqDDW2w&list=RDAMVM1K0N7UaZpz8"))
