# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './res/ui/youtubesigninwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YouTubeSignInWindow(object):
    def setupUi(self, YouTubeSignInWindow):
        YouTubeSignInWindow.setObjectName("YouTubeSignInWindow")
        YouTubeSignInWindow.resize(502, 357)
        self.verticalLayout = QtWidgets.QVBoxLayout(YouTubeSignInWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(YouTubeSignInWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(YouTubeSignInWindow)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.email = QtWidgets.QLineEdit(YouTubeSignInWindow)
        self.email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.email.setObjectName("email")
        self.verticalLayout.addWidget(self.email)
        self.password = QtWidgets.QLineEdit(YouTubeSignInWindow)
        self.password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.rememberMe = QtWidgets.QCheckBox(YouTubeSignInWindow)
        self.rememberMe.setObjectName("rememberMe")
        self.verticalLayout.addWidget(self.rememberMe)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(YouTubeSignInWindow)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(YouTubeSignInWindow)
        self.buttonBox.accepted.connect(YouTubeSignInWindow.accept) # type: ignore
        self.buttonBox.rejected.connect(YouTubeSignInWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(YouTubeSignInWindow)

    def retranslateUi(self, YouTubeSignInWindow):
        _translate = QtCore.QCoreApplication.translate
        YouTubeSignInWindow.setWindowTitle(_translate("YouTubeSignInWindow", "Sign in"))
        self.label.setText(_translate("YouTubeSignInWindow", "Sign in"))
        self.label_2.setText(_translate("YouTubeSignInWindow", "Authentication is required for download songs with age restrictions."))
        self.email.setPlaceholderText(_translate("YouTubeSignInWindow", "Email"))
        self.password.setPlaceholderText(_translate("YouTubeSignInWindow", "Password"))
        self.rememberMe.setText(_translate("YouTubeSignInWindow", "Remember me"))
