# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './res/ui/ytmusicsetupwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YtMusicSetupWindow(object):
    def setupUi(self, YtMusicSetupWindow):
        YtMusicSetupWindow.setObjectName("YtMusicSetupWindow")
        YtMusicSetupWindow.resize(603, 383)
        self.verticalLayout = QtWidgets.QVBoxLayout(YtMusicSetupWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(YtMusicSetupWindow)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pasteArea = QtWidgets.QPlainTextEdit(YtMusicSetupWindow)
        self.pasteArea.setObjectName("pasteArea")
        self.verticalLayout.addWidget(self.pasteArea)
        self.buttons = QtWidgets.QDialogButtonBox(YtMusicSetupWindow)
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.verticalLayout.addWidget(self.buttons)

        self.retranslateUi(YtMusicSetupWindow)
        self.buttons.accepted.connect(YtMusicSetupWindow.accept) # type: ignore
        self.buttons.rejected.connect(YtMusicSetupWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(YtMusicSetupWindow)

    def retranslateUi(self, YtMusicSetupWindow):
        _translate = QtCore.QCoreApplication.translate
        YtMusicSetupWindow.setWindowTitle(_translate("YtMusicSetupWindow", "YTMusic Setup"))
        self.label.setText(_translate("YtMusicSetupWindow", "<html><head/><body><p>YouTube Music requires authenticated requests: follow the instructions at <a href=\"https://ytmusicapi.readthedocs.io/en/latest/setup.html\"><span style=\" text-decoration: underline; color:#4285f4;\">ytmusicapi.</span></a></p><p>Go to <a href=\"https://music.youtube.com\"><span style=\" text-decoration: underline; color:#4285f4;\">https://music.youtube.com</span></a> (ensure you are logged in).</p><p>Find an authenticated POST request (filter by <span style=\" font-family:\'Monospace\';\">/browse</span> using the search bar of the developer tools).</p><p>Copy the request headers and paste here below.</p></body></html>"))
