# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './res/ui/imagepreviewwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImagePreviewWindow(object):
    def setupUi(self, ImagePreviewWindow):
        ImagePreviewWindow.setObjectName("ImagePreviewWindow")
        ImagePreviewWindow.resize(509, 436)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ImagePreviewWindow.sizePolicy().hasHeightForWidth())
        ImagePreviewWindow.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ImagePreviewWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image = QtWidgets.QLabel(ImagePreviewWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("./res/ui/../images/questionmark.png"))
        self.image.setScaledContents(True)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.horizontalLayout.addWidget(self.image)

        self.retranslateUi(ImagePreviewWindow)
        QtCore.QMetaObject.connectSlotsByName(ImagePreviewWindow)

    def retranslateUi(self, ImagePreviewWindow):
        _translate = QtCore.QCoreApplication.translate
        ImagePreviewWindow.setWindowTitle(_translate("ImagePreviewWindow", "Dialog"))
